package com.example.web_qltv_be.security;

public class Endpoints {

    public static final String font_end_host = "http://localhost:3000";
    public static final String[] PUBLIC_GET = {
            "/books",
            "/books/**",
            "/genre/**",
            "/images/**",
            "/reviews/**",
            "/users/search/existsByUsername/**",
            "/users/search/existsByEmail/**",
            "/user/active-account/**",
            "/cart-items/**",
            "/users/*/listCartItems",
            "/users/*/libraryCard",
            "/orders/**",
            "/order-detail/**",
            "/users/*/listOrders",
            "/users/*/listRoles",
            "/users/*",
            "/library-cards/**",
            "/library-card/**",
            "/library-card/*",
            "/library-cards/*/borrowRecords",
            "/favorite-book/get-favorite-book/**",
            "/users/*/listFavoriteBooks",
            "/favorite-books/*/book",
            "/deliveries/**",
            "/vnpay/**",
            "/borrow-record/get-by-library-card/**",
            "/borrow-records/**",
            "borrow-records/*/borrowRecordDetails",
            "/borrow-records/search/findBorrowRecordsByLibraryCard_CardNumber",
            "/borrow-record-detail/**",
            "/library-violation-types/**",
            "/ddc-categories/**",
            "/book-items/**",
            "/book/book-items/**",
            "/borrow-record-details/**",
            "/statistics/top-borrowed-books?limit=3",
            "violation-types",
            "/book/book-items/available/1"
    };

    public static final String[] PUBLIC_POST = {
            "/user/register",
            "/user/authenticate",
            "/cart-item/add-item",
            "/order/**",
            "/review/add-review/**",
            "/feedback/add-feedback",
            "/favorite-book/add-book",
            "/vnpay/create-payment/**",
            "/review/get-review/**",
            "/borrow-record/add-borrow-record",
            "/library-card/create",
            "library-card-violation/**",
    };

    public static final String[] PUBLIC_PUT = {
            "/cart-item/**",
            "/cart-items/**",
            "/users/**",
            "/user/update-profile",
            "/user/change-password",
            "/user/forgot-password",
            "/user/change-avatar",
            "/order/update-order",
            "/order/cancel-order",
            "/review/update-review",
            "/borrow-record/update-borrow-record",
            "/borrow-record/cancel-borrow-record",
            "/library-card/create",
            "/library-card/sendRequestRenewCard",

    };

    public static final String[] PUBLIC_DELETE = {
            "/cart-items/**",
            "/favorite-book/delete-book",
    };

    public static final String[] ADMIN_ENDPOINT = {
            "/users",
            "/users/**",
            "/cart-items/**",
            "/books",
            "/books/**",
            "/book/add-book/**",
            "/user/add-user/**",
            "/feedbacks/**",
            "/cart-items/**",
            "/cart-item/**",
            "/orders/**",
            "/order/**",
            "/order-detail/**",
            "/roles/**",
            "/favorite-book/**",
            "/favorite-books/**",
            "/review/**",
            "/book/get-total/**",
            "/feedbacks/search/countBy/**",
            "/borrow-record/**",
            "/borrow-records/**",
            "/library-card/**",
            "library-violation-types/**",
            "library-card-violation/**",
            "/ddc-categories/**",
            "/book-items/**",
            "/statistics/**",
            "/user/toggle-status/**",
            "/user/update-roles/**",
            "/borrow-record-detail/**",
            "/borrow-record-detail/search/**",
            "/book-item/**",
            "/**",
    };
}